stages:
 - dockerize

dockerize:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker build . -t localhost:5005/node_docker
  - docker push localhost:5005/node_docker
