stages:
 - dockerize

dockerize:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker build . -t registry:5000/node_docker
  - docker push registry:5000/node_docker
