stages:
 - dockerize

dockerize:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker build . -t registry/node_docker
  - docker push registry/node_docker
