stages:
 - dockerize

dockerize:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker build . -t docker.mytcc.be/node_docker
  - docker push docker.mytcc.be/node_docker
