stages:
 - dockerize

dockerize:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker build . -t node_docker
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker.tircher.be
  - docker tag node_docker docker.tircher.be/node_docker
  - docker push docker.tircher.be/node_docker